Categorize some plugins
Hecter94/EndlessSky-PluginArchive pull request #198
Opened 2024-10-28 06:33 UTC by TheGiraffe3

Makes a new "Starts" category.

2024-10-28 07:04 UTC, zuckung commented
test worked fine.

template.txt needs more changes
line 129 and 139, other categories are like `[Story](%webroot%res/mds/story.md) (%story%)`  
and you have just `[Starts](%webroot%res/md/starts.md)` so the replacement of the plugin amount is missing.

also the categories are in 3 rows of 4 categories each (till now), and you added a 5th to the 3rd row. so for the eye, make it 3 rows of 4 and a 4th row with a single. not sure about the look, maybe 2 rows with 6 and 7 categories.

2024-10-28 09:13 UTC, zuckung commented
plugins which add starts:

DevStarts
better.starts
Difficulties
Lampyrid Start
Advanced Starts
Alternate Start Luna
Space Shuttle Start
AuldrStarts

2024-10-28 09:18 UTC, zuckung commented
and to add plugin via issue:

.github/ISSUE_TEMPLATE/plugin-submission.yml line 46

2024-10-28 09:24 UTC, TheGiraffe3 commented
Please co-author zuckung if/when you merge this.

2024-10-28 09:39 UTC, zuckung commented
and planet.map doesn't have a start anymore, and it was more story than just a start.
might need some discussion if only pure starts should be in here or plugins which add lots other things and require using the start too.

2024-10-28 09:40 UTC, TheGiraffe3 commented on res/pluginlist/planet.map.txt
> +category=Starts
```suggestion
category=Story
```

2024-10-28 16:23 UTC, TheGiraffe3 commented on res/pluginlist/Galactic Conquest.txt
> +category=Status
```suggestion
category=Starts
```

2024-10-29 12:16 UTC, Hecter94 requested changes
Can you please remove all of the unrelated changes from this PR? 
You can open them in a new PR if you want to.

2024-10-29 12:21 UTC, TheGiraffe3 commented
By "unrelated changes" I assume you mean typo fixes?

2024-10-29 12:26 UTC, Hecter94 commented
> By "unrelated changes" I assume you mean typo fixes?

Anything that isn't part of adding this new category, yes.

2024-10-29 12:32 UTC, TheGiraffe3 commented on res/pluginlist/Difficulties.txt
> +description=Adds three different difficulties that take form as the start to a game. Not recomended for people new to Endless Sky.
```suggestion
description=Adds three diffrent difficulties that take form as the start to a game. Not reccomended for people new to Endless Sky.
```

2024-10-29 12:32 UTC, TheGiraffe3 commented on res/pluginlist/Difficulties.txt
> +description=Adds three diffrent difficulties that take form as the start to a game. Not reccomended for people new to Endless Sky.
```suggestion
description=Adds three diffrent difficulties that take form as the start to a game. Not reccomended for people new to Endless Sky.

```

2024-10-29 12:33 UTC, TheGiraffe3 commented on res/pluginlist/better.starts.txt
> +description=Adds several new start options with different ships, background storys, credits and debts. See the readme for details.
```suggestion
description=Adds several new start options with different ships, background storys, credits and debts. See the readme for details.

```

2024-10-29 14:08 UTC, merged